reference: /some/path/my-source-file.mxf
models:
  - HD
resolutions:
  - width: 1920
    height: 1080
bitrates:
  - 0
pipeline:
  ffmpegEncoder: libx265
  singlePass: true
  skipDefaultOptions: true
  ffmpegOptions:
    '-pix_fmt': 'yuv420p'
    '-preset': 'veryslow'
    '-x265-params': 'crf=%CRF%:scenecut=0:keyint=50:min-keyint=50:open-gop=0'
  easyVmafExtraArgs:
    '-threads': 20
pipelineVariables:
  CRF:
    - 22
    - 26
    - 30
    - 34
